# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
language: en-US
tone_instructions: "Only provide helpful, relevant comments. Be brief and terse but clear."
early_access: true
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: false
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  assess_linked_issues: false
  estimate_code_review_effort: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  in_progress_fortune: false
  poem: false
  labeling_instructions:
    - label: ""
      instructions: ""
  path_filters: []
  path_instructions:
    - path: "**/*.{c,h}"
      instructions: |
        - `gr_vec_*()` functions cannot fail. No need to check their return value.
        - `gr_vec_free(x)` always sets `x = NULL`. There is no risk of double free.
        - `ec_node_*()` functions consume their `ec_node` arguments. No leaks on error.
        - `rte_node->ctx` is an uint8_t array of size 16, not a pointer.
        - Don't suggest to replace `assert()` with graceful error checking.
        - We compile with `-std=gnu2x`. Unnamed parameters in function definitions are *valid*.
    - path: "**/*.sh"
      instructions: |
        - Don't bother about unquoted shell variables.
    - path: "**/*.md"
      instructions: |
        - Never comment about setext vs ATX style headings.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
      config_file: ""
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
      config_file: ""
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
      config_file: ""
    eslint:
      enabled: true
    flake8:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
      config_file: ""
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
      config_file: ""
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: ""
        instructions: ""
  unit_tests:
    path_instructions:
      - path: ""
        instructions: ""
