# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
language: en-US
tone_instructions: "Only comment on critical issues, bugs, or security concerns. Skip style suggestions and minor observations."
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  high_level_summary: false
  review_status: false
  commit_status: false
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  in_progress_fortune: false
  poem: false
  path_instructions:
    - path: "**/*.{c,h}"
      instructions: |
        - `gr_vec_*()` functions cannot fail. No need to check their return value.
        - `gr_vec_free(x)` always sets `x = NULL`. There is no risk of double free.
        - `ec_node_*()` functions consume their `ec_node` arguments. No leaks on error.
        - `rte_node->ctx` is an uint8_t array of size 16, not a pointer.
        - Never suggest to replace `assert()` with graceful error checking.
        - We compile with `-std=gnu2x`. Unnamed parameters in function definitions are *valid*.
    - path: "**/*.sh"
      instructions: |
        - Don't bother about unquoted shell variables.
    - path: "**/*.md"
      instructions: |
        - Never comment about setext vs ATX style headings.
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: off
    description:
      mode: off
    issue_assessment:
      mode: off
chat:
  art: false
