# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
name: Bug Report
description: File a bug report.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Make sure to check if a similar bug wasn't already reported and/or
        fixed by searching through existing issues and pull requests (including
        closed ones).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please describe what is the issue with as much detail as possible.
        Include any relevant logs, error messages and/or core dump backtraces.
        Also include what are the steps to reproduce the problem.
      placeholder: Bug description...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of grout is the bug observed on?
      placeholder: grout --version
    validations:
      required: true
