# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Robin Jarry

[binaries]
c = ['ccache', 'powerpc64le-linux-gnu-gcc']
cpp = ['ccache', 'powerpc64le-linux-gnu-g++']
ar = 'powerpc64le-linux-gnu-ar'
strip = 'powerpc64le-linux-gnu-strip'
pkg-config = '/usr/bin/pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'ppc64'
cpu = 'power8'
endian = 'little'

[properties]
platform = 'generic'
pkg_config_libdir = '/usr/lib/powerpc64le-linux-gnu/pkgconfig'

[dpdk:project options]
platform = 'generic'
enable_drivers = 'net/null'
