#!/usr/bin/env python3
# pylint: disable=invalid-name

import glob
import os
import sys


here = os.path.dirname(__file__)
build_dir = os.path.join(here, "../build/cli")

if os.path.isdir(build_dir) and glob.glob(os.path.join(build_dir, "_br*.so")):
    for d in glob.iglob(os.path.join(here, "../modules/*/cli")):
        sys.path.insert(0, d)
    sys.path.insert(0, build_dir)

import br.__main__


br.__main__.main()
