# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Robin Jarry
# ex: ft=systemd

# systemd drop-in for frr.service

[Unit]
After=grout.service

[Service]
JoinsNamespaceOf=grout.service
PrivateNetwork=true
