// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2024 Robin Jarry

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// API request header.
struct gr_api_request {
	uint32_t id; // Auto-generated by client
	uint32_t type;
	uint32_t payload_len; // max GR_API_MAX_MSG_LEN
};

// API response header.
struct gr_api_response {
	uint32_t for_id; // matches gr_api_request.id (for out-of-order handling)
	uint32_t status; // errno values, 0 for success
	uint32_t payload_len; // max GR_API_MAX_MSG_LEN
};

#define GR_API_MAX_MSG_LEN (128 * 1024)

#define REQUEST_TYPE(module, id) (((uint32_t)(0xffff & module) << 16) | (0xffff & id))
#define EVENT_TYPE(module, id) (((uint32_t)(0xffff & module) << 16) | (0xffff & id))
#define EVENT_TYPE_ALL UINT32_C(0xffffffff)

#define GR_DEFAULT_SOCK_PATH "/run/grout.sock"

// Opaque API client handle (NOT thread-safe, use one per thread).
struct gr_api_client;

// Connect to the API server.
// Automatically sends GR_MAIN_HELLO with version negotiation.
// Returns NULL on failure (check errno for details).
struct gr_api_client *gr_api_client_connect(const char *sock_path);

// Disconnect from the API server.
// Automatically unsubscribes from all events.
int gr_api_client_disconnect(struct gr_api_client *);

// Send an API request.
// Returns request ID on success, negative errno on failure.
// Client handles out-of-order responses automatically.
long int
gr_api_client_send(struct gr_api_client *, uint32_t req_type, size_t tx_len, const void *tx_data);

// Receive an API response.
// Caller must free(*rx_data) after use.
// Returns 0 on success, negative errno on failure.
int gr_api_client_recv(struct gr_api_client *, uint32_t for_id, void **rx_data);

// Send a request and receive the response.
// Convenience function for simple request-response patterns.
// Caller must free(*rx_data) after use.
// Returns 0 on success, negative errno on failure.
static inline int gr_api_client_send_recv(
	struct gr_api_client *client,
	uint32_t req_type,
	size_t tx_len,
	const void *tx_data,
	void **rx_data
) {
	long int ret = gr_api_client_send(client, req_type, tx_len, tx_data);
	if (ret < 0)
		return ret;
	return gr_api_client_recv(client, ret, rx_data);
}

// Send a request and iterate over the received stream of responses.
//
// @param obj Iterator variable (const pointer to response object type).
// @param ret Final return code of the operation.
// @param client API client handle.
// @param req_type Request type code.
// @param tx_len Request payload size (0 if tx_data is NULL).
// @param tx_data Request payload (NULL if tx_len is 0).
//
// This should be used like a for loop, e.g.:
//
//     struct gr_infra_iface_list_req req = {.type = GR_IFACE_TYPE_UNDEF};
//     const struct gr_iface *iface;
//     int ret;
//
//     gr_api_client_stream_foreach (iface, ret, client, GR_INFRA_IFACE_LIST, sizeof(req), &req)
//         printf("Interface: %s\n", iface->name);
//     if (ret < 0)
//         handle_error(ret);
//
// XXX: Interrupting the loop with break or an early return will cause memory leaks
// and will leave messages hanging in the socket buffer. Make sure to let the loop
// terminate gracefully.
#define gr_api_client_stream_foreach(obj, ret, client, req_type, tx_len, tx_data)                  \
	for (long int __id = gr_api_client_send(client, req_type, tx_len, tx_data), __first = 1;   \
	     ({                                                                                    \
		     if (__first == 1)                                                             \
			     ret = __id;                                                           \
		     __id >= 0 && __first; /* statement expression value */                        \
	     });                                                                                   \
	     __first = 0)                                                                          \
		for (void *__ptr = NULL; ({                                                        \
			     bool more = false;                                                    \
			     ret = gr_api_client_recv(client, __id, &__ptr);                       \
			     if (ret < 0) {                                                        \
				     free(__ptr);                                                  \
				     __ptr = NULL;                                                 \
			     } else if (__ptr != NULL) {                                           \
				     obj = __ptr;                                                  \
				     more = true;                                                  \
			     }                                                                     \
			     more; /* statement expression value */                                \
		     });                                                                           \
		     free(__ptr), __ptr = NULL)

#define GR_MAIN_MODULE 0xcafe

// Client handshake with version negotiation.
// Must be the first request sent by any client.
// Version string must match server version exactly.
#define GR_MAIN_HELLO REQUEST_TYPE(GR_MAIN_MODULE, 0x1981)
struct gr_hello_req {
	char version[128]; // NUL-terminated
};
// struct gr_hello_resp { };

// Subscribe to events of a given type.
// Use EVENT_TYPE_ALL to subscribe to all event types.
// Multiple subscriptions to same type update suppression flag.
#define GR_MAIN_EVENT_SUBSCRIBE REQUEST_TYPE(GR_MAIN_MODULE, 0xcafe)
struct gr_event_subscribe_req {
	// Suppress events originating from API messages made by the same PID
	// as the subscriber socket.
	bool suppress_self_events;
	uint32_t ev_type;
};
// struct gr_event_subscribe_resp { };

// Unsubscribe from all events.
// Removes ALL subscriptions for this client, not just specific types.
// Automatically called on client disconnection.
#define GR_MAIN_EVENT_UNSUBSCRIBE REQUEST_TYPE(GR_MAIN_MODULE, 0xcaff)
// struct gr_event_unsubscribe_req { };
// struct gr_event_unsubscribe_resp { };

struct gr_api_event {
	uint32_t ev_type;
	size_t payload_len;
};

// Receive an event notification.
// Caller must free(*event) after use.
// Returns 0 on success, negative errno on failure.
int gr_api_client_event_recv(const struct gr_api_client *, struct gr_api_event **);
