# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Christophe Fontaine
# Copyright (c) 2023 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          dnf install -y \
            make ninja-build meson dpdk-devel clang-analyzer clang-tools-extra \
            protobuf-c-compiler protobuf-c-devel libevent-devel
      - run: |
          curl -LO https://git.dpdk.org/dpdk/plain/buildtools/dpdk-cmdline-gen.py
          chmod 755 dpdk-cmdline-gen.py
          mv dpdk-cmdline-gen.py /usr/local/bin
      - run: make
      - run: make lint
