# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Christophe Fontaine
# Copyright (c) 2023 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: >
          sudo apt install --no-install-recommends
            make meson ninja-build libdpdk-dev clang-format
      - run: make
      - run: ./build/brouter
      - run: make lint
