# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          dnf install -y \
            make gcc ninja-build meson clang-tools-extra git gcovr scdoc \
            libasan \
            libcmocka-devel \
            libedit-devel \
            libevent-devel \
            numactl-devel \
            python3-pyelftools
      - run: make
      - run: make lint
      - run: make coverage
