# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: |
          dnf install -y \
            make gcc ninja-build meson git gcovr scdoc \
            libasan \
            libcmocka-devel \
            libedit-devel \
            libevent-devel \
            numactl-devel \
            python3-pyelftools
      - uses: actions/checkout@v4
      - run: make
      - run: make coverage
  lint:
    runs-on: ubuntu-latest
    container: debian:testing
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: |
          apt-get update
          apt-get install -y make clang-format git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: make lint
      - run: |
          echo $${{github.event}}
          git config --global --add safe.directory $PWD
          git log --oneline --decorate "origin/${{ github.base_ref }}..${{ github.ref }}"
        if: ${{ github.base_ref && github.ref }}
