# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Christophe Fontaine
# Copyright (c) 2023 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends meson ninja-build
      - run: meson setup build
      - run: ninja -C build
