# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      SANITIZE: address
      BUILDTYPE: debugoptimized
    steps:
      - name: install system dependencies
        run: |
          set -xe
          sudo apt-get update -qy
          sudo apt-get install -qy \
            make gcc ccache ninja-build meson git scdoc \
            libasan8 libcmocka-dev libedit-dev \
            libevent-dev libsmartcols-dev libnuma-dev python3-pyelftools
          echo "PATH=/usr/lib/ccache:$PATH" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/br
            build/br-cli
            build/subprojects/ecoli/src/libecoli.so
          retention-days: 5
      - run: make unit-tests
  smoke:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: install system dependencies
        run: |
          set -xe
          sudo apt-get update -qy
          sudo apt-get install -qy \
            git socat tcpdump \
            iproute2 iputils-ping libasan8 libedit2 \
            libevent-2.1-7t64 libsmartcols1 libnuma1
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
      - run: chmod -c a+x build/br* build/subprojects/ecoli/src/libecoli.so
      - run: sudo smoke/run.sh build
  lint:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: dnf install -y make clang-tools-extra git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: make lint
        # TODO: later, check commit messages here
      - run: |
          git config --global --add safe.directory $PWD
          git log --oneline --decorate "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        if: ${{ github.event.pull_request.base.sha && github.event.pull_request.head.sha }}
