# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          dnf install -y \
            make gcc ninja-build meson dpdk-devel clang-tools-extra \
            libevent-devel libedit-devel git
      - run: make
      - run: make lint
