# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --device=/dev/net/tun --privileged
    env:
      CC: ccache gcc
    steps:
      - run: |
          dnf install -y \
            make gcc ccache ninja-build meson git gcovr scdoc \
            socat \
            iproute \
            iputils \
            libasan \
            libcmocka-devel \
            libedit-devel \
            libevent-devel \
            libsmartcols-devel \
            numactl-devel \
            python3-pyelftools
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.ccache
      - run: make
      - run: make coverage
  lint:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: dnf install -y make clang-tools-extra git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: make lint
        # TODO: later, check commit messages here
      - run: |
          git config --global --add safe.directory $PWD
          git log --oneline --decorate "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        if: ${{ github.event.pull_request.base.sha && github.event.pull_request.head.sha }}
