# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: Publish

permissions:
  contents: read

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  check:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml

  package:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/package.yml

  upload:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-24.04
    needs:
      - check
      - package
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-packages"
          merge-multiple: true
      - uses: docker/metadata-action@v5
        name: Extract metadata for the Docker image
        id: meta
        with:
          images: "quay.io/grout/grout"
          tags: |
              type=edge,branch=main
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ github.token }}
          tag: "edge"
          files: |
            grout*.rpm
            grout*.*deb
