# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Robin Jarry
---
name: Publish

permissions:
  contents: read

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check.yml

  deb:
    permissions:
      actions: write
    runs-on: ubuntu-24.04
    container: "debian:stable"
    steps:
      - name: install system dependencies
        run: |
          set -xe
          apt-get update -qy
          NEEDRESTART_MODE=l apt-get install -qy --no-install-recommends \
            git build-essential meson ninja-build pkgconf scdoc python3-pyelftools \
            libcmocka-dev libedit-dev libevent-dev libnuma-dev \
            libsmartcols-dev libarchive-dev libibverbs-dev \
            bash-completion devscripts debhelper
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # force fetch all history
          persist-credentials: false
      - run: git config --global --add safe.directory $PWD
      - run: make deb
      - uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: grout*.deb
          retention-days: 5

  rpm:
    permissions:
      actions: write
    runs-on: ubuntu-24.04
    container: "quay.io/centos/centos:stream9"
    steps:
      - name: install system dependencies
        run: |
          set -xe
          dnf --enablerepo=crb install -y --nodocs --setopt=install_weak_deps=0 \
            https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
          dnf --enablerepo=crb install -y --nodocs --setopt=install_weak_deps=0 \
            gcc git make meson ninja-build pkgconf scdoc python3-pyelftools \
            libcmocka-devel libedit-devel libevent-devel numactl-devel \
            libsmartcols-devel libarchive-devel rdma-core-devel \
            rpm-build systemd
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # force fetch all history
          persist-credentials: false
      - run: git config --global --add safe.directory $PWD
      - run: make rpm
      - uses: actions/upload-artifact@v4
        with:
          name: rpm-packages
          path: grout*.rpm
          retention-days: 5

  upload:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-24.04
    needs:
      - deb
      - rpm
      - smoke
      - lint
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-packages"
          merge-multiple: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          tags: "ghcr.io/dpdk/grout:edge"
          push: true
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ github.token }}
          tag: "edge"
          files: |
            grout.x86_64.rpm
            grout-devel.noarch.rpm
            grout-debuginfo.x86_64.rpm
            grout-debugsource.x86_64.rpm
            grout_amd64.deb
            grout-dev_all.deb
            grout-dbgsym_amd64.deb
