# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry

name: GPT Inline Code Review

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install openai requests

      - uses: actions/checkout@v4

      - name: Download PR diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Accept: application/vnd.github.v3.diff" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -L "${{ github.event.pull_request.diff_url }}" \
            -o pr.diff

      - name: Run GPT inline review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
          DIFF_FILE: pr.diff
        run: python3 .github/workflows/ai-review.py
