# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
name: Review

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Review approved
        run: echo "PR approved by ${{ github.event.review.user.login }}"
